.TH ddcutil-service 1 "ddcutil-service" "MH" \" -*- nroff -*-
.SH NAME
ddcutil-service \- D-Bus service for libddcutil VESA DDC Monitor Virtual Control Panel
.SH SYNOPSIS

.B ddcutil-service
.I --help
|
.I --version
|
.I --introspect
.br
.B ddcutil-service
[
.B --prefer-polling
]
|
[
.B --polling-interval \fIseconds\fP
]
|
[
.B --disable-signals
]
|
[
.B --lock
]
|
[
.B --log-info
]
[
.B --ddca-syslog-level \fIN\fP
]
|
[
.B --ddca-init-options \fIM\fP
]
[
.B -- \fIlibddcutil ddc_init options...\fP
]

.SH DESCRIPTION
.B ddcutil-service
ddcutil-service is D-Bus service wrapper for libddcutil which
implements the VESA DDC Monitor Control Command Set.  In general,
most things that can be controlled using a monitor's on-screen
display can be controlled by this service.

.P
The
.B ddctuil-service
is registered as a
.B session-service
with the
.B dbus-daemon
which starts the service on demand.
Should the service error and terminate, the
.B dbus-daemon
will automatically restart it when it is next accessed.  Client
connections with the service are stateless.

.SS OPTIONS

.TP
.B "--help"

Outputs options-help and exits.

.TP
.B "--version"

Outputs the service interface version and the
.B libddcutil
version and exits.

.TP
.B "--introspect"

Outputs the XML introspection text for the service and exits.

.TP
.B "--prefer-polling"

Set polling to be the preferred method for detecting display connectivity changes.
Normally polling is the a fallback used if a GPU-driver does
not support DMA or does not provide the change-detection features
required by
.B libddcutil.
Polling will probably work with any GPU.

.TP
.B "--poll-interval" \fIseconds\fP

If polling is enabled, this option defines how often to check for display
connectivity changes.  Default 30 seconds,  minimum 10 seconds, zero to disable polling.

.TP
.B "--disable-signals"

Disable all display connectivity change detection and disable the
.B ConnectDisplaysChanged signal
sent to clients.
This cannot be reversed without restarting the service.

.TP
.B "--lock"

Make all service properties and sleep-multipliers readonly so
that clients cannot change them. This options provides a way to
lockdown the service to the configuration passed on the command line.
The lock is provided to assist with managing conflicts
when more than one ddcutil application is in use at the same time.

.TP
.B "--log_info"

Enabling log-info will produce info and debug level output.  The
out put will go to standard-error or, if running from
.B dbus-daemon,
to the journal.
This option can also be toggled after startup by using B-Bus
to alter the
service's
.B ServiceInfoLogging
property (see
.B EXAMPLES
below).

.TP
.B "--ddca-syslog-level" \fIN\fP

The DDCA syslog level numerical value is passed to
.B libddutil's ddca_init()
function at startup to enable logging from within the library.
It's only available for
.B libddutil version 2.1.0
and up.
Values for
.B N
are
.B 0:never, 2:error:, 6:warning, 9:notice, 12:info, 15:verbose, and 18:debug.

.TP
.B "--ddca-init-options" \fIN\fP

The DDCA init option is a numerical value is passed to
.B libddutil ddca_init()
function at startup to enable/disable various options with the library.
It's only available for
.B libddutil 2.1.0+.

.TP
.B -- \fIlibddcutil ddc_init options...\fP

The
.B libddcutil
library also supports its own extensive set of init options, any arguments following
.B --
will be passed as to
.B libddutil ddca_init()
function at service startup.

.SH SERVICE METHODS

.PP
The following is a brief summary of the methods provided by the service.


.TP
.B Detect
Return a list of monitors detected along with their properties.

.TP
.B GetVcp
Query a displays's settings by VCP code, for example, bightness is VCP code 0x10.

.TP
.B GetMultipleVcp
Query multiple VCP codes for a single display.

.TP
.B SetVcp
Set a display's settings by VCP code.

.TP
.B GetCapabiltiesMetadata
Query a displays capabilities returning a parsed data-structure describing the
features and permitted values.

.TP
.B GetCapabilitiesString
Query a displays capabilities returning a unparsed capabilities string.

.TP
.B GetVcpMetadata
Query the metadata describing a specific VCP code for a specific display.

.TP
.B GetSleepMultiplier
Get the display specific
.B ddcutil
sleep multiplier.

.TP
.B SetSleepMultiplier
Set a display specific
.B ddcutil
sleep multiplier.

.TP
.B Restart
Restart the service with specific arguments.

.PP
If a method requires a display-argument, either an integer
.I display-number
or a
.I base64-encoded EDID
can be supplied. Base64-encoded EDIDs are obtained from the
.B Detect
method.  If a EDID is supplied, a method's
.B flags
option can be set to
.B EDID_PREFIX
(1),
this indicates a unique prefix of an EDID has been passed rather than
the entire string (this makes using EDIDs from the command line a little easier).

Run
.B ddcutil-service --introspect
for details on each method's in/out parameters. For even more
information the
.B d-feet
graphical D-Bus debugger provides a very readable
way to browse and experiment with the service interface, simply start
.B d-feet,
select the
.B Session Bus
and search for
.B ddcutil-service.

.SH SERVICE SIGNALS

The service may raise a
.B ConnectedDisplaysChanged
D-Bus signal when a display undergoes a connection status change.
.PP
Not all displays, GPU's, GPU-drivers, or cabling, provide the necessary support
for this feature.  Results may also vary depending on the mix of desktop components,
such as KDE, Gnome, X11, and Wayland.  Depending on all of these factors,
status changes may be signaled for all/some/none of display-cable connect/disconnect,
power on/off, and DPMS wake/sleep.
.PP
Full support for this callback requires
.B ddcutil/libddcutil version 2.1.0+ and a GPU and driver configured for DRM.

Should a GPU lack the necessary features, the service may automatically fallback to
polling by using DDC detect.  Polling provides basic support for detecting
connectivity and power-switch changes.
If necessary polling can be forced by the
.B --prefer-polling
option.  Depending on factors such as GPU, display and cabling, even change
detection by polling may not work.

.SH SERVICE PROPERTIES

The service provides several D-Bus accessible properties for querying
and adjusting its operation.

.TP
.B AttributesReturnedByDetect
Query the fieldnames returned from the
.B Detect
method.  Lists the names of the fields in the order they are
found in each struct returned from
.B Detect.

.TP
.B StatusValues
Query the list of status values returned by
.B libddcutil
along with their text names.

.TP
.B DisplayEventTypes
List the event-types sent by the
.B ConnectedDisplaysChanged
signal along with their text names.
Events are included for display connection/disconnection (hotplug), DPMS-sleep, and DPMS-wake.
If the list is empty, the GPU, GPU-driver, or
.B libddcutil
version doesn't support display event detection.

.TP
.B DdcutilDynamicSleep
Enable/disable
.B libddcutil
dynamic-sleep adjustment of DDC timings.

.TP
.B DdcutilOutputLevel
Read/write the
.B libddcutil
output level.

.TP
.B DdcutilVerifySetVcp
Enable/disable
.B libddcutil
extra DDC calls to check whether VCP settings were actually applied by the monitor.

.TP
.B DdcutilVersion
Query the
.B libddcutil
version string.

.TP
.B ServiceMuteSignals
Set this property to true to mute the signals emitted by the service.
Any
.B libddcutil
managed event-detection threads created at service startup
will continue to run, but no signals will be emitted.  Any
internal service polling will be suspended.  Set to true
to unmute.

.TP
.B ServiceInfoLogging
Enable/disable the service's diagnostic level output to include info and debug messages.
Not that
.B libddcutil
also has a logging mechanism (see
.B libddcutil ddc_init options
)

.TP
.B ServiceInterfaceVersion
Query the service interface version.

.TP
.B ServiceFlagOptions
List the available flag option values that can be passed to service methods.
Not all options are applicable to all methods.

.TP
.B ServiceParametersLocked
Returns whether the
.I --lock
command line argument has been used to make all properties and sleep-multipliers read-only.

.TP
.B ServicePollInterval
Query or set the display change detection poll interval (minimum 10, zero to disable polling).

.PP
Properties can be queried and set using utilities such as
.B busctl,
.B d-bus-send,
and
.B d-feet,
see
.B EXAMPLES.

.SH CONFIG FILES

If running via the dbus-daemon, when the service is requested, the
dbus-daemon consults the service definition in:

.B     /usr/share/dbus-1/services/com.ddcutil.DdcutilService.service
.PP
Typically the contents would be as follows

.nf
    [D-BUS Service]
    Name=com.ddcutil.DdcutilService
    Exec=/usr/bin/ddcutil-service
.fi

Any service options can be appended to the
.B Exec
line.

If you wish to install the service for use by a single user,
on many Linux distributions, the dbus-daemon first looks for the session service
config-file in:

.B $HOME/.local/share/dbus-1/services/com.ddcutil.DdcutilService.service

When initialised at service startup, the
.B libddcutil
library loads options from
.B $HOME/.config/ddcutil/ddcutilrc
at startup, see
.I https://www.ddcutil.com/config_file/
for details.


.SH EXAMPLES
.PP
The systemd utility
.B bustctl
can be used from the command line to interact with the service.

.B Summarise the service methods and properties:

.nf
    busctl --user introspect com.ddcutil.DdcutilService /com/ddcutil/DdcutilObject
.fi

.B Detect the connected displays:

.nf
    busctl --user call com.ddcutil.DdcutilService /com/ddcutil/DdcutilObject \\
        com.ddcutil.DdcutilInterface Detect u 0
.fi

.B Get the brightness of display-1 (VCP 0x10):

.nf
    busctl --user call com.ddcutil.DdcutilService /com/ddcutil/DdcutilObject \\
        com.ddcutil.DdcutilInterface GetVcp isyu 1 "" 0x10 0
.fi

.B Set brightness of display-1 (VCP 0x10):

.nf
    busctl --user call com.ddcutil.DdcutilService /com/ddcutil/DdcutilObject \\
        com.ddcutil.DdcutilInterface SetVcp isyqu 1 "" 16 50 0
.fi

.B Query or set the service logging level:

.nf
   busctl --user get-property com.ddcutil.DdcutilService /com/ddcutil/DdcutilObject \\
       com.ddcutil.DdcutilInterface ServiceInfoLogging

   busctl --user set-property com.ddcutil.DdcutilService /com/ddcutil/DdcutilObject \\
       com.ddcutil.DdcutilInterface ServiceInfoLogging b true
.fi

.PP
The installed service is packaged with several examples of it's use, including
.B dbus-send
scripts
and
.B python3
clients for D-Bus
.B dasbus
and
.B QtDBus
APIs.  The examples are normally be installed in:
.B /usr/share/ddcutil-service/examples/


.fi

.SH LIMITATIONS

Support for the
.B ConnectedDisplaysChanged
signal depends on features within the GPU and GPU-Driver.

Some GPU drivers and VDUs have buggy DDC implementations. If you have the choice,
a DisplayPort to DisplayPort connection may work more reliably than DVI or HDMI.

Some
.libddcutil
parameters can only be changed at process startup.  The service can be
restarted either by killing it with a UNIX signal, or by invoking the
service's
.B Restart
menthod.


.SH REPORTING BUGS

.I https://github.com/digitaltrails/ddcutil-service/issues


.SH AUTHOR
Michael Hamilton

.SH ACKNOWLEDGEMENTS

Thanks go out to
.B Sanford Rockowitz
for
.B libddcutil,
.B ddcutil
and all the assistance and advice provided during the development of this service.

Thanks also to
.B Michal Suchanek
for assistance with the OpenSUSE RPM spec.

.SH COPYRIGHT
Copyright (C) 2023 Michael Hamilton.

.B ddcutil-service
is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.



